// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package dbsqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertBlindWrite = `-- name: InsertBlindWrite :batchexec
INSERT INTO tx_blind_writes (block_num, tx_num, ns_id, seq_num, key, value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (block_num, tx_num, ns_id, seq_num) DO NOTHING
`

type InsertBlindWriteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertBlindWriteParams struct {
	BlockNum int64  `json:"block_num"`
	TxNum    int64  `json:"tx_num"`
	NsID     string `json:"ns_id"`
	SeqNum   int32  `json:"seq_num"`
	Key      []byte `json:"key"`
	Value    []byte `json:"value"`
}

func (q *Queries) InsertBlindWrite(ctx context.Context, arg []InsertBlindWriteParams) *InsertBlindWriteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.SeqNum,
			a.Key,
			a.Value,
		}
		batch.Queue(insertBlindWrite, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertBlindWriteBatchResults{br, len(arg), false}
}

func (b *InsertBlindWriteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertBlindWriteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertReadOnly = `-- name: InsertReadOnly :batchexec
INSERT INTO tx_reads_only (block_num, tx_num, ns_id, seq_num, key, version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (block_num, tx_num, ns_id, seq_num) DO NOTHING
`

type InsertReadOnlyBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertReadOnlyParams struct {
	BlockNum int64       `json:"block_num"`
	TxNum    int64       `json:"tx_num"`
	NsID     string      `json:"ns_id"`
	SeqNum   int32       `json:"seq_num"`
	Key      []byte      `json:"key"`
	Version  pgtype.Int8 `json:"version"`
}

func (q *Queries) InsertReadOnly(ctx context.Context, arg []InsertReadOnlyParams) *InsertReadOnlyBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.SeqNum,
			a.Key,
			a.Version,
		}
		batch.Queue(insertReadOnly, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertReadOnlyBatchResults{br, len(arg), false}
}

func (b *InsertReadOnlyBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertReadOnlyBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertReadWrite = `-- name: InsertReadWrite :batchexec
INSERT INTO tx_read_writes (block_num, tx_num, ns_id, seq_num, key, read_version, value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (block_num, tx_num, ns_id, seq_num) DO NOTHING
`

type InsertReadWriteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertReadWriteParams struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	SeqNum      int32       `json:"seq_num"`
	Key         []byte      `json:"key"`
	ReadVersion pgtype.Int8 `json:"read_version"`
	Value       []byte      `json:"value"`
}

func (q *Queries) InsertReadWrite(ctx context.Context, arg []InsertReadWriteParams) *InsertReadWriteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.SeqNum,
			a.Key,
			a.ReadVersion,
			a.Value,
		}
		batch.Queue(insertReadWrite, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertReadWriteBatchResults{br, len(arg), false}
}

func (b *InsertReadWriteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertReadWriteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTransaction = `-- name: InsertTransaction :batchexec
INSERT INTO transactions (
    block_num, tx_num, tx_id, validation_code, tx_type, chaincode_name,
    creator_msp_id, creator_id_bytes, creator_nonce, envelope_signature,
    chaincode_proposal_input, tx_response_status, tx_response_message,
    tx_response_payload, payload_proposal_hash, payload_extension, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (block_num, tx_num) DO NOTHING
`

type InsertTransactionBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTransactionParams struct {
	BlockNum               int64            `json:"block_num"`
	TxNum                  int64            `json:"tx_num"`
	TxID                   []byte           `json:"tx_id"`
	ValidationCode         int16            `json:"validation_code"`
	TxType                 pgtype.Int2      `json:"tx_type"`
	ChaincodeName          pgtype.Text      `json:"chaincode_name"`
	CreatorMspID           pgtype.Text      `json:"creator_msp_id"`
	CreatorIDBytes         []byte           `json:"creator_id_bytes"`
	CreatorNonce           []byte           `json:"creator_nonce"`
	EnvelopeSignature      []byte           `json:"envelope_signature"`
	ChaincodeProposalInput []byte           `json:"chaincode_proposal_input"`
	TxResponseStatus       pgtype.Int4      `json:"tx_response_status"`
	TxResponseMessage      pgtype.Text      `json:"tx_response_message"`
	TxResponsePayload      []byte           `json:"tx_response_payload"`
	PayloadProposalHash    []byte           `json:"payload_proposal_hash"`
	PayloadExtension       []byte           `json:"payload_extension"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg []InsertTransactionParams) *InsertTransactionBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.TxID,
			a.ValidationCode,
			a.TxType,
			a.ChaincodeName,
			a.CreatorMspID,
			a.CreatorIDBytes,
			a.CreatorNonce,
			a.EnvelopeSignature,
			a.ChaincodeProposalInput,
			a.TxResponseStatus,
			a.TxResponseMessage,
			a.TxResponsePayload,
			a.PayloadProposalHash,
			a.PayloadExtension,
			a.CreatedAt,
		}
		batch.Queue(insertTransaction, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTransactionBatchResults{br, len(arg), false}
}

func (b *InsertTransactionBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTransactionBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxEndorsement = `-- name: InsertTxEndorsement :batchexec
INSERT INTO tx_endorsements (block_num, tx_num, ns_id, seq_num, endorsement, msp_id, identity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (block_num, tx_num, ns_id, seq_num) DO NOTHING
`

type InsertTxEndorsementBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxEndorsementParams struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	SeqNum      int32       `json:"seq_num"`
	Endorsement []byte      `json:"endorsement"`
	MspID       pgtype.Text `json:"msp_id"`
	Identity    []byte      `json:"identity"`
}

func (q *Queries) InsertTxEndorsement(ctx context.Context, arg []InsertTxEndorsementParams) *InsertTxEndorsementBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.SeqNum,
			a.Endorsement,
			a.MspID,
			a.Identity,
		}
		batch.Queue(insertTxEndorsement, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxEndorsementBatchResults{br, len(arg), false}
}

func (b *InsertTxEndorsementBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxEndorsementBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxNamespace = `-- name: InsertTxNamespace :batchexec
INSERT INTO tx_namespaces (block_num, tx_num, ns_id, ns_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (block_num, tx_num, ns_id) DO NOTHING
`

type InsertTxNamespaceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxNamespaceParams struct {
	BlockNum  int64  `json:"block_num"`
	TxNum     int64  `json:"tx_num"`
	NsID      string `json:"ns_id"`
	NsVersion int64  `json:"ns_version"`
}

func (q *Queries) InsertTxNamespace(ctx context.Context, arg []InsertTxNamespaceParams) *InsertTxNamespaceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.NsVersion,
		}
		batch.Queue(insertTxNamespace, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxNamespaceBatchResults{br, len(arg), false}
}

func (b *InsertTxNamespaceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxNamespaceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertNamespacePolicy = `-- name: UpsertNamespacePolicy :batchexec
INSERT INTO namespace_policies (namespace, version, policy)
VALUES ($1, $2, $3)
ON CONFLICT (namespace, version) DO UPDATE SET policy = EXCLUDED.policy
`

type UpsertNamespacePolicyBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertNamespacePolicyParams struct {
	Namespace string `json:"namespace"`
	Version   int64  `json:"version"`
	Policy    []byte `json:"policy"`
}

func (q *Queries) UpsertNamespacePolicy(ctx context.Context, arg []UpsertNamespacePolicyParams) *UpsertNamespacePolicyBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Namespace,
			a.Version,
			a.Policy,
		}
		batch.Queue(upsertNamespacePolicy, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertNamespacePolicyBatchResults{br, len(arg), false}
}

func (b *UpsertNamespacePolicyBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertNamespacePolicyBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
