// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package dbsqlc

import (
	"context"
)

const getBlock = `-- name: GetBlock :one
SELECT block_num, tx_count, previous_hash, data_hash
FROM blocks
WHERE block_num = $1
`

func (q *Queries) GetBlock(ctx context.Context, blockNum int64) (Block, error) {
	row := q.db.QueryRow(ctx, getBlock, blockNum)
	var i Block
	err := row.Scan(
		&i.BlockNum,
		&i.TxCount,
		&i.PreviousHash,
		&i.DataHash,
	)
	return i, err
}

const getBlockHeight = `-- name: GetBlockHeight :one
SELECT COALESCE(MAX(block_num), 0) AS height
FROM blocks
`

func (q *Queries) GetBlockHeight(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getBlockHeight)
	var height interface{}
	err := row.Scan(&height)
	return height, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (block_num, tx_count, previous_hash, data_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (block_num) DO NOTHING
`

type InsertBlockParams struct {
	BlockNum     int64  `json:"block_num"`
	TxCount      int32  `json:"tx_count"`
	PreviousHash []byte `json:"previous_hash"`
	DataHash     []byte `json:"data_hash"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.BlockNum,
		arg.TxCount,
		arg.PreviousHash,
		arg.DataHash,
	)
	return err
}
