// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockNum     int64  `json:"block_num"`
	TxCount      int32  `json:"tx_count"`
	PreviousHash []byte `json:"previous_hash"`
	DataHash     []byte `json:"data_hash"`
}

type NamespacePolicy struct {
	ID        int64  `json:"id"`
	Namespace string `json:"namespace"`
	Version   int64  `json:"version"`
	Policy    []byte `json:"policy"`
}

type Transaction struct {
	ID             int64  `json:"id"`
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int64  `json:"validation_code"`
}

type TxEndorsement struct {
	ID            int64       `json:"id"`
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Endorsement   []byte      `json:"endorsement"`
	MspID         pgtype.Text `json:"msp_id"`
	Identity      []byte      `json:"identity"`
}

type TxNamespace struct {
	ID            int64  `json:"id"`
	TransactionID int64  `json:"transaction_id"`
	NsID          string `json:"ns_id"`
	NsVersion     int64  `json:"ns_version"`
}

type TxRead struct {
	ID            int64       `json:"id"`
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Key           []byte      `json:"key"`
	Version       pgtype.Int8 `json:"version"`
	IsReadWrite   bool        `json:"is_read_write"`
}

type TxWrite struct {
	ID            int64       `json:"id"`
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Key           []byte      `json:"key"`
	Value         []byte      `json:"value"`
	IsBlindWrite  bool        `json:"is_blind_write"`
	ReadVersion   pgtype.Int8 `json:"read_version"`
}
