// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type Block struct {
	BlockNum     int64  `json:"block_num"`
	TxCount      int32  `json:"tx_count"`
	PreviousHash []byte `json:"previous_hash"`
	DataHash     []byte `json:"data_hash"`
}

type Namespace struct {
	ID   int64  `json:"id"`
	Name []byte `json:"name"`
}

type Transaction struct {
	ID             int64  `json:"id"`
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int64  `json:"validation_code"`
}

type Writeset struct {
	ID          int64  `json:"id"`
	NamespaceID int64  `json:"namespace_id"`
	BlockNum    int64  `json:"block_num"`
	TxNum       int64  `json:"tx_num"`
	TxID        []byte `json:"tx_id"`
	Key         []byte `json:"key"`
	Value       []byte `json:"value"`
	IsDelete    bool   `json:"is_delete"`
}
