// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockNum     int64  `json:"block_num"`
	TxCount      int32  `json:"tx_count"`
	PreviousHash []byte `json:"previous_hash"`
	DataHash     []byte `json:"data_hash"`
}

type Namespace struct {
	ID   int64  `json:"id"`
	Name []byte `json:"name"`
}

type Transaction struct {
	ID             int64  `json:"id"`
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int64  `json:"validation_code"`
}

type TxNamespace struct {
	ID            int64  `json:"id"`
	TransactionID int64  `json:"transaction_id"`
	NsID          string `json:"ns_id"`
	NsVersion     int64  `json:"ns_version"`
}

type TxRead struct {
	ID            int64       `json:"id"`
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Key           []byte      `json:"key"`
	Version       pgtype.Int8 `json:"version"`
	IsReadWrite   bool        `json:"is_read_write"`
}

type TxWrite struct {
	ID            int64       `json:"id"`
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Key           []byte      `json:"key"`
	Value         []byte      `json:"value"`
	IsBlindWrite  bool        `json:"is_blind_write"`
	ReadVersion   pgtype.Int8 `json:"read_version"`
}

type Writeset struct {
	ID          int64  `json:"id"`
	NamespaceID int64  `json:"namespace_id"`
	BlockNum    int64  `json:"block_num"`
	TxNum       int64  `json:"tx_num"`
	TxID        []byte `json:"tx_id"`
	Key         []byte `json:"key"`
	Value       []byte `json:"value"`
}
