// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: namespaces.sql

package dbsqlc

import (
	"context"
)

const upsertNamespace = `-- name: UpsertNamespace :one
INSERT INTO namespaces (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertNamespace(ctx context.Context, name []byte) (int64, error) {
	row := q.db.QueryRow(ctx, upsertNamespace, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
