// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	GetBlock(ctx context.Context, blockNum int64) (Block, error)
	GetBlockHeight(ctx context.Context) (interface{}, error)
	GetTransactionByTxID(ctx context.Context, txID []byte) (Transaction, error)
	GetTransactionID(ctx context.Context, arg GetTransactionIDParams) (int64, error)
	GetTransactionsByBlock(ctx context.Context, arg GetTransactionsByBlockParams) ([]Transaction, error)
	GetWritesByTx(ctx context.Context, arg GetWritesByTxParams) ([]Writeset, error)
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	InsertTxNamespace(ctx context.Context, arg InsertTxNamespaceParams) (int64, error)
	InsertTxRead(ctx context.Context, arg InsertTxReadParams) error
	InsertTxWrite(ctx context.Context, arg InsertTxWriteParams) error
	InsertWrite(ctx context.Context, arg InsertWriteParams) error
	UpsertNamespace(ctx context.Context, name []byte) (int64, error)
}

var _ Querier = (*Queries)(nil)
