// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	GetBlindWritesByTx(ctx context.Context, arg GetBlindWritesByTxParams) ([]GetBlindWritesByTxRow, error)
	GetBlock(ctx context.Context, blockNum int64) (Block, error)
	GetBlockHeight(ctx context.Context) (interface{}, error)
	GetEndorsementsByTx(ctx context.Context, arg GetEndorsementsByTxParams) ([]GetEndorsementsByTxRow, error)
	GetNamespacePolicies(ctx context.Context, namespace string) ([]NamespacePolicy, error)
	GetReadWritesByTx(ctx context.Context, arg GetReadWritesByTxParams) ([]GetReadWritesByTxRow, error)
	GetReadsOnlyByTx(ctx context.Context, arg GetReadsOnlyByTxParams) ([]GetReadsOnlyByTxRow, error)
	GetValidationCodeByBlock(ctx context.Context, arg GetValidationCodeByBlockParams) ([]Transaction, error)
	GetValidationCodeByTxID(ctx context.Context, txID []byte) (Transaction, error)
	InsertBlindWrite(ctx context.Context, arg []InsertBlindWriteParams) *InsertBlindWriteBatchResults
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	InsertReadOnly(ctx context.Context, arg []InsertReadOnlyParams) *InsertReadOnlyBatchResults
	InsertReadWrite(ctx context.Context, arg []InsertReadWriteParams) *InsertReadWriteBatchResults
	InsertTransaction(ctx context.Context, arg []InsertTransactionParams) *InsertTransactionBatchResults
	InsertTxEndorsement(ctx context.Context, arg []InsertTxEndorsementParams) *InsertTxEndorsementBatchResults
	InsertTxNamespace(ctx context.Context, arg []InsertTxNamespaceParams) *InsertTxNamespaceBatchResults
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]Block, error)
	UpsertNamespacePolicy(ctx context.Context, arg []UpsertNamespacePolicyParams) *UpsertNamespacePolicyBatchResults
}

var _ Querier = (*Queries)(nil)
