// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbsqlc

import (
	"context"
)

const getTransactionByTxID = `-- name: GetTransactionByTxID :one
SELECT id, block_num, tx_num, tx_id, validation_code
FROM transactions
WHERE tx_id = $1
`

func (q *Queries) GetTransactionByTxID(ctx context.Context, txID []byte) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByTxID, txID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BlockNum,
		&i.TxNum,
		&i.TxID,
		&i.ValidationCode,
	)
	return i, err
}

const getTransactionsByBlock = `-- name: GetTransactionsByBlock :many
SELECT id, block_num, tx_num, tx_id, validation_code
FROM transactions
WHERE block_num = $1
ORDER BY tx_num
LIMIT $2 OFFSET $3
`

type GetTransactionsByBlockParams struct {
	BlockNum int64 `json:"block_num"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) GetTransactionsByBlock(ctx context.Context, arg GetTransactionsByBlockParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByBlock, arg.BlockNum, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.BlockNum,
			&i.TxNum,
			&i.TxID,
			&i.ValidationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (block_num, tx_num, tx_id, validation_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (block_num, tx_num) DO NOTHING
`

type InsertTransactionParams struct {
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int64  `json:"validation_code"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.BlockNum,
		arg.TxNum,
		arg.TxID,
		arg.ValidationCode,
	)
	return err
}
