// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbsqlc

import (
	"context"
)

const getValidationCodeByBlock = `-- name: GetValidationCodeByBlock :many
SELECT
    block_num, tx_num, tx_id, validation_code, tx_type, chaincode_name,
    creator_msp_id, creator_id_bytes, creator_nonce, envelope_signature,
    chaincode_proposal_input, tx_response_status, tx_response_message,
    tx_response_payload, payload_proposal_hash, payload_extension, created_at
FROM transactions
WHERE block_num = $1
ORDER BY tx_num
LIMIT $2 OFFSET $3
`

type GetValidationCodeByBlockParams struct {
	BlockNum int64 `json:"block_num"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) GetValidationCodeByBlock(ctx context.Context, arg GetValidationCodeByBlockParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getValidationCodeByBlock, arg.BlockNum, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.BlockNum,
			&i.TxNum,
			&i.TxID,
			&i.ValidationCode,
			&i.TxType,
			&i.ChaincodeName,
			&i.CreatorMspID,
			&i.CreatorIDBytes,
			&i.CreatorNonce,
			&i.EnvelopeSignature,
			&i.ChaincodeProposalInput,
			&i.TxResponseStatus,
			&i.TxResponseMessage,
			&i.TxResponsePayload,
			&i.PayloadProposalHash,
			&i.PayloadExtension,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidationCodeByTxID = `-- name: GetValidationCodeByTxID :one
SELECT
    block_num, tx_num, tx_id, validation_code, tx_type, chaincode_name,
    creator_msp_id, creator_id_bytes, creator_nonce, envelope_signature,
    chaincode_proposal_input, tx_response_status, tx_response_message,
    tx_response_payload, payload_proposal_hash, payload_extension, created_at
FROM transactions
WHERE tx_id = $1
`

func (q *Queries) GetValidationCodeByTxID(ctx context.Context, txID []byte) (Transaction, error) {
	row := q.db.QueryRow(ctx, getValidationCodeByTxID, txID)
	var i Transaction
	err := row.Scan(
		&i.BlockNum,
		&i.TxNum,
		&i.TxID,
		&i.ValidationCode,
		&i.TxType,
		&i.ChaincodeName,
		&i.CreatorMspID,
		&i.CreatorIDBytes,
		&i.CreatorNonce,
		&i.EnvelopeSignature,
		&i.ChaincodeProposalInput,
		&i.TxResponseStatus,
		&i.TxResponseMessage,
		&i.TxResponsePayload,
		&i.PayloadProposalHash,
		&i.PayloadExtension,
		&i.CreatedAt,
	)
	return i, err
}
