// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_blind_writes.sql

package dbsqlc

import (
	"context"
)

const getBlindWritesByTx = `-- name: GetBlindWritesByTx :many
SELECT ns_id, key, value
FROM tx_blind_writes
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id, key
`

type GetBlindWritesByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetBlindWritesByTxRow struct {
	NsID  string `json:"ns_id"`
	Key   []byte `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) GetBlindWritesByTx(ctx context.Context, arg GetBlindWritesByTxParams) ([]GetBlindWritesByTxRow, error) {
	rows, err := q.db.Query(ctx, getBlindWritesByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlindWritesByTxRow{}
	for rows.Next() {
		var i GetBlindWritesByTxRow
		if err := rows.Scan(&i.NsID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
