// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_endorsements.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndorsementsByTx = `-- name: GetEndorsementsByTx :many
SELECT te.id, te.endorsement, te.msp_id, te.identity, tn.ns_id
FROM tx_endorsements te
JOIN tx_namespaces tn ON te.tx_namespace_id = tn.id
JOIN transactions t ON tn.transaction_id = t.id
WHERE t.block_num = $1 AND t.tx_num = $2
ORDER BY te.id
`

type GetEndorsementsByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetEndorsementsByTxRow struct {
	ID          int64       `json:"id"`
	Endorsement []byte      `json:"endorsement"`
	MspID       pgtype.Text `json:"msp_id"`
	Identity    []byte      `json:"identity"`
	NsID        string      `json:"ns_id"`
}

func (q *Queries) GetEndorsementsByTx(ctx context.Context, arg GetEndorsementsByTxParams) ([]GetEndorsementsByTxRow, error) {
	rows, err := q.db.Query(ctx, getEndorsementsByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEndorsementsByTxRow{}
	for rows.Next() {
		var i GetEndorsementsByTxRow
		if err := rows.Scan(
			&i.ID,
			&i.Endorsement,
			&i.MspID,
			&i.Identity,
			&i.NsID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTxEndorsement = `-- name: InsertTxEndorsement :exec
INSERT INTO tx_endorsements (tx_namespace_id, endorsement, msp_id, identity)
VALUES ($1, $2, $3, $4)
`

type InsertTxEndorsementParams struct {
	TxNamespaceID int64       `json:"tx_namespace_id"`
	Endorsement   []byte      `json:"endorsement"`
	MspID         pgtype.Text `json:"msp_id"`
	Identity      []byte      `json:"identity"`
}

func (q *Queries) InsertTxEndorsement(ctx context.Context, arg InsertTxEndorsementParams) error {
	_, err := q.db.Exec(ctx, insertTxEndorsement,
		arg.TxNamespaceID,
		arg.Endorsement,
		arg.MspID,
		arg.Identity,
	)
	return err
}
