// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_reads.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReadsByTx = `-- name: GetReadsByTx :many
SELECT tr.id, tr.key, tr.version, tr.is_read_write, tn.ns_id
FROM tx_reads tr
JOIN tx_namespaces tn ON tr.tx_namespace_id = tn.id
JOIN transactions t ON tn.transaction_id = t.id
WHERE t.block_num = $1 AND t.tx_num = $2
ORDER BY tr.id
`

type GetReadsByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetReadsByTxRow struct {
	ID          int64       `json:"id"`
	Key         []byte      `json:"key"`
	Version     pgtype.Int8 `json:"version"`
	IsReadWrite bool        `json:"is_read_write"`
	NsID        string      `json:"ns_id"`
}

func (q *Queries) GetReadsByTx(ctx context.Context, arg GetReadsByTxParams) ([]GetReadsByTxRow, error) {
	rows, err := q.db.Query(ctx, getReadsByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReadsByTxRow{}
	for rows.Next() {
		var i GetReadsByTxRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsReadWrite,
			&i.NsID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
