// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: writesets.sql

package dbsqlc

import (
	"context"
)

const insertWrite = `-- name: InsertWrite :exec
INSERT INTO writesets
(namespace_id, block_num, tx_num, tx_id, key, value)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertWriteParams struct {
	NamespaceID int64  `json:"namespace_id"`
	BlockNum    int64  `json:"block_num"`
	TxNum       int64  `json:"tx_num"`
	TxID        []byte `json:"tx_id"`
	Key         []byte `json:"key"`
	Value       []byte `json:"value"`
}

func (q *Queries) InsertWrite(ctx context.Context, arg InsertWriteParams) error {
	_, err := q.db.Exec(ctx, insertWrite,
		arg.NamespaceID,
		arg.BlockNum,
		arg.TxNum,
		arg.TxID,
		arg.Key,
		arg.Value,
	)
	return err
}
