// Copyright IBM Corp. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: api/proto/explorer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockExplorerService_GetBlockHeight_FullMethodName       = "/explorerv1.BlockExplorerService/GetBlockHeight"
	BlockExplorerService_ListBlocks_FullMethodName           = "/explorerv1.BlockExplorerService/ListBlocks"
	BlockExplorerService_GetBlockDetail_FullMethodName       = "/explorerv1.BlockExplorerService/GetBlockDetail"
	BlockExplorerService_GetTransactionDetail_FullMethodName = "/explorerv1.BlockExplorerService/GetTransactionDetail"
	BlockExplorerService_GetNamespacePolicies_FullMethodName = "/explorerv1.BlockExplorerService/GetNamespacePolicies"
)

// BlockExplorerServiceClient is the client API for BlockExplorerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockExplorerServiceClient interface {
	GetBlockHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBlockHeightResponse, error)
	ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error)
	GetBlockDetail(ctx context.Context, in *GetBlockDetailRequest, opts ...grpc.CallOption) (*BlockDetail, error)
	GetTransactionDetail(ctx context.Context, in *GetTxDetailRequest, opts ...grpc.CallOption) (*TxDetail, error)
	GetNamespacePolicies(ctx context.Context, in *GetNamespacePoliciesRequest, opts ...grpc.CallOption) (*GetNamespacePoliciesResponse, error)
}

type blockExplorerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockExplorerServiceClient(cc grpc.ClientConnInterface) BlockExplorerServiceClient {
	return &blockExplorerServiceClient{cc}
}

func (c *blockExplorerServiceClient) GetBlockHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBlockHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockHeightResponse)
	err := c.cc.Invoke(ctx, BlockExplorerService_GetBlockHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerServiceClient) ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlocksResponse)
	err := c.cc.Invoke(ctx, BlockExplorerService_ListBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerServiceClient) GetBlockDetail(ctx context.Context, in *GetBlockDetailRequest, opts ...grpc.CallOption) (*BlockDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockDetail)
	err := c.cc.Invoke(ctx, BlockExplorerService_GetBlockDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerServiceClient) GetTransactionDetail(ctx context.Context, in *GetTxDetailRequest, opts ...grpc.CallOption) (*TxDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxDetail)
	err := c.cc.Invoke(ctx, BlockExplorerService_GetTransactionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerServiceClient) GetNamespacePolicies(ctx context.Context, in *GetNamespacePoliciesRequest, opts ...grpc.CallOption) (*GetNamespacePoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespacePoliciesResponse)
	err := c.cc.Invoke(ctx, BlockExplorerService_GetNamespacePolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockExplorerServiceServer is the server API for BlockExplorerService service.
// All implementations must embed UnimplementedBlockExplorerServiceServer
// for forward compatibility.
type BlockExplorerServiceServer interface {
	GetBlockHeight(context.Context, *emptypb.Empty) (*GetBlockHeightResponse, error)
	ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error)
	GetBlockDetail(context.Context, *GetBlockDetailRequest) (*BlockDetail, error)
	GetTransactionDetail(context.Context, *GetTxDetailRequest) (*TxDetail, error)
	GetNamespacePolicies(context.Context, *GetNamespacePoliciesRequest) (*GetNamespacePoliciesResponse, error)
	mustEmbedUnimplementedBlockExplorerServiceServer()
}

// UnimplementedBlockExplorerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockExplorerServiceServer struct{}

func (UnimplementedBlockExplorerServiceServer) GetBlockHeight(context.Context, *emptypb.Empty) (*GetBlockHeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockHeight not implemented")
}
func (UnimplementedBlockExplorerServiceServer) ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocks not implemented")
}
func (UnimplementedBlockExplorerServiceServer) GetBlockDetail(context.Context, *GetBlockDetailRequest) (*BlockDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockDetail not implemented")
}
func (UnimplementedBlockExplorerServiceServer) GetTransactionDetail(context.Context, *GetTxDetailRequest) (*TxDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionDetail not implemented")
}
func (UnimplementedBlockExplorerServiceServer) GetNamespacePolicies(context.Context, *GetNamespacePoliciesRequest) (*GetNamespacePoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespacePolicies not implemented")
}
func (UnimplementedBlockExplorerServiceServer) mustEmbedUnimplementedBlockExplorerServiceServer() {}
func (UnimplementedBlockExplorerServiceServer) testEmbeddedByValue()                              {}

// UnsafeBlockExplorerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockExplorerServiceServer will
// result in compilation errors.
type UnsafeBlockExplorerServiceServer interface {
	mustEmbedUnimplementedBlockExplorerServiceServer()
}

func RegisterBlockExplorerServiceServer(s grpc.ServiceRegistrar, srv BlockExplorerServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockExplorerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockExplorerService_ServiceDesc, srv)
}

func _BlockExplorerService_GetBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServiceServer).GetBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorerService_GetBlockHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServiceServer).GetBlockHeight(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorerService_ListBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServiceServer).ListBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorerService_ListBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServiceServer).ListBlocks(ctx, req.(*ListBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorerService_GetBlockDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServiceServer).GetBlockDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorerService_GetBlockDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServiceServer).GetBlockDetail(ctx, req.(*GetBlockDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorerService_GetTransactionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServiceServer).GetTransactionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorerService_GetTransactionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServiceServer).GetTransactionDetail(ctx, req.(*GetTxDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorerService_GetNamespacePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespacePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServiceServer).GetNamespacePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorerService_GetNamespacePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServiceServer).GetNamespacePolicies(ctx, req.(*GetNamespacePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockExplorerService_ServiceDesc is the grpc.ServiceDesc for BlockExplorerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockExplorerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explorerv1.BlockExplorerService",
	HandlerType: (*BlockExplorerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockHeight",
			Handler:    _BlockExplorerService_GetBlockHeight_Handler,
		},
		{
			MethodName: "ListBlocks",
			Handler:    _BlockExplorerService_ListBlocks_Handler,
		},
		{
			MethodName: "GetBlockDetail",
			Handler:    _BlockExplorerService_GetBlockDetail_Handler,
		},
		{
			MethodName: "GetTransactionDetail",
			Handler:    _BlockExplorerService_GetTransactionDetail_Handler,
		},
		{
			MethodName: "GetNamespacePolicies",
			Handler:    _BlockExplorerService_GetNamespacePolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/explorer.proto",
}
