// Copyright IBM Corp. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/explorer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightResponse) Reset() {
	*x = GetBlockHeightResponse{}
	mi := &file_api_proto_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightResponse) ProtoMessage() {}

func (x *GetBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlockHeightResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_api_proto_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *ListBlocksRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ListBlocksRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ListBlocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBlocksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type BlockSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxCount       int32                  `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	DataHash      []byte                 `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSummary) Reset() {
	*x = BlockSummary{}
	mi := &file_api_proto_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSummary) ProtoMessage() {}

func (x *BlockSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSummary.ProtoReflect.Descriptor instead.
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *BlockSummary) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockSummary) GetTxCount() int32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockSummary) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *BlockSummary) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockSummary        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_api_proto_explorer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *ListBlocksResponse) GetBlocks() []*BlockSummary {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GetBlockDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxLimit       int32                  `protobuf:"varint,2,opt,name=tx_limit,json=txLimit,proto3" json:"tx_limit,omitempty"`
	TxOffset      int32                  `protobuf:"varint,3,opt,name=tx_offset,json=txOffset,proto3" json:"tx_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockDetailRequest) Reset() {
	*x = GetBlockDetailRequest{}
	mi := &file_api_proto_explorer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockDetailRequest) ProtoMessage() {}

func (x *GetBlockDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockDetailRequest.ProtoReflect.Descriptor instead.
func (*GetBlockDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockDetailRequest) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *GetBlockDetailRequest) GetTxLimit() int32 {
	if x != nil {
		return x.TxLimit
	}
	return 0
}

func (x *GetBlockDetailRequest) GetTxOffset() int32 {
	if x != nil {
		return x.TxOffset
	}
	return 0
}

type BlockDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxCount       int32                  `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	DataHash      []byte                 `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Transactions  []*TxDetail            `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDetail) Reset() {
	*x = BlockDetail{}
	mi := &file_api_proto_explorer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDetail) ProtoMessage() {}

func (x *BlockDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDetail.ProtoReflect.Descriptor instead.
func (*BlockDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *BlockDetail) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockDetail) GetTxCount() int32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockDetail) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *BlockDetail) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

func (x *BlockDetail) GetTransactions() []*TxDetail {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// GetTxDetailRequest identifies a transaction by its hex-encoded ID.
//
// The hex encoding is URL-safe, so callers can copy the tx_id directly
// from REST responses into the /transactions/{tx_id} path parameter
// without additional base64 or URL encoding steps.
type GetTxDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // hex-encoded transaction ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxDetailRequest) Reset() {
	*x = GetTxDetailRequest{}
	mi := &file_api_proto_explorer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxDetailRequest) ProtoMessage() {}

func (x *GetTxDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTxDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *GetTxDetailRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// TxDetail describes a single transaction.  The tx_id field is hex-encoded
// so that it is safe to embed directly in URLs and is consistent with
// GetTxDetailRequest.
type TxDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockNum       int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum          int64                  `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	TxId           string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // hex-encoded transaction ID
	ValidationCode int32                  `protobuf:"varint,4,opt,name=validation_code,json=validationCode,proto3" json:"validation_code,omitempty"`
	BlindWrites    []*BlindWriteRow       `protobuf:"bytes,5,rep,name=blind_writes,json=blindWrites,proto3" json:"blind_writes,omitempty"`
	Endorsements   []*EndorsementRow      `protobuf:"bytes,6,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	ReadWrites     []*ReadWriteRow        `protobuf:"bytes,7,rep,name=read_writes,json=readWrites,proto3" json:"read_writes,omitempty"`
	ReadsOnly      []*ReadOnlyRow         `protobuf:"bytes,8,rep,name=reads_only,json=readsOnly,proto3" json:"reads_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TxDetail) Reset() {
	*x = TxDetail{}
	mi := &file_api_proto_explorer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxDetail) ProtoMessage() {}

func (x *TxDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxDetail.ProtoReflect.Descriptor instead.
func (*TxDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{7}
}

func (x *TxDetail) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *TxDetail) GetTxNum() int64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *TxDetail) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TxDetail) GetValidationCode() int32 {
	if x != nil {
		return x.ValidationCode
	}
	return 0
}

func (x *TxDetail) GetBlindWrites() []*BlindWriteRow {
	if x != nil {
		return x.BlindWrites
	}
	return nil
}

func (x *TxDetail) GetEndorsements() []*EndorsementRow {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

func (x *TxDetail) GetReadWrites() []*ReadWriteRow {
	if x != nil {
		return x.ReadWrites
	}
	return nil
}

func (x *TxDetail) GetReadsOnly() []*ReadOnlyRow {
	if x != nil {
		return x.ReadsOnly
	}
	return nil
}

type BlindWriteRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlindWriteRow) Reset() {
	*x = BlindWriteRow{}
	mi := &file_api_proto_explorer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindWriteRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindWriteRow) ProtoMessage() {}

func (x *BlindWriteRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindWriteRow.ProtoReflect.Descriptor instead.
func (*BlindWriteRow) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{8}
}

func (x *BlindWriteRow) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *BlindWriteRow) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BlindWriteRow) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type EndorsementRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Endorsement   []byte                 `protobuf:"bytes,2,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	MspId         *string                `protobuf:"bytes,3,opt,name=msp_id,json=mspId,proto3,oneof" json:"msp_id,omitempty"`
	Identity      []byte                 `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementRow) Reset() {
	*x = EndorsementRow{}
	mi := &file_api_proto_explorer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementRow) ProtoMessage() {}

func (x *EndorsementRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementRow.ProtoReflect.Descriptor instead.
func (*EndorsementRow) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{9}
}

func (x *EndorsementRow) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *EndorsementRow) GetEndorsement() []byte {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

func (x *EndorsementRow) GetMspId() string {
	if x != nil && x.MspId != nil {
		return *x.MspId
	}
	return ""
}

func (x *EndorsementRow) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ReadWriteRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ReadVersion   *int64                 `protobuf:"varint,3,opt,name=read_version,json=readVersion,proto3,oneof" json:"read_version,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRow) Reset() {
	*x = ReadWriteRow{}
	mi := &file_api_proto_explorer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRow) ProtoMessage() {}

func (x *ReadWriteRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRow.ProtoReflect.Descriptor instead.
func (*ReadWriteRow) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{10}
}

func (x *ReadWriteRow) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *ReadWriteRow) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadWriteRow) GetReadVersion() int64 {
	if x != nil && x.ReadVersion != nil {
		return *x.ReadVersion
	}
	return 0
}

func (x *ReadWriteRow) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReadOnlyRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version       *int64                 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOnlyRow) Reset() {
	*x = ReadOnlyRow{}
	mi := &file_api_proto_explorer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOnlyRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOnlyRow) ProtoMessage() {}

func (x *ReadOnlyRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOnlyRow.ProtoReflect.Descriptor instead.
func (*ReadOnlyRow) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{11}
}

func (x *ReadOnlyRow) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *ReadOnlyRow) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadOnlyRow) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type GetNamespacePoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespacePoliciesRequest) Reset() {
	*x = GetNamespacePoliciesRequest{}
	mi := &file_api_proto_explorer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespacePoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespacePoliciesRequest) ProtoMessage() {}

func (x *GetNamespacePoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespacePoliciesRequest.ProtoReflect.Descriptor instead.
func (*GetNamespacePoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{12}
}

func (x *GetNamespacePoliciesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NamespacePolicyRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`                                    // human-readable policy expression, e.g. "1-of(Org1MSP.peer)" or channel config policy tree
	Certificates  []string               `protobuf:"bytes,4,rep,name=certificates,proto3" json:"certificates,omitempty"`                        // PEM-encoded X.509 certificates
	MspIds        []string               `protobuf:"bytes,5,rep,name=msp_ids,json=mspIds,proto3" json:"msp_ids,omitempty"`                      // e.g. ["org", "OrdererMSP"]
	Endpoints     []string               `protobuf:"bytes,6,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                              // e.g. ["localhost:7050"]
	HashAlgorithm string                 `protobuf:"bytes,7,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"` // e.g. "SHA256"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacePolicyRow) Reset() {
	*x = NamespacePolicyRow{}
	mi := &file_api_proto_explorer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacePolicyRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacePolicyRow) ProtoMessage() {}

func (x *NamespacePolicyRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacePolicyRow.ProtoReflect.Descriptor instead.
func (*NamespacePolicyRow) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{13}
}

func (x *NamespacePolicyRow) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacePolicyRow) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NamespacePolicyRow) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *NamespacePolicyRow) GetCertificates() []string {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *NamespacePolicyRow) GetMspIds() []string {
	if x != nil {
		return x.MspIds
	}
	return nil
}

func (x *NamespacePolicyRow) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NamespacePolicyRow) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

type GetNamespacePoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*NamespacePolicyRow  `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespacePoliciesResponse) Reset() {
	*x = GetNamespacePoliciesResponse{}
	mi := &file_api_proto_explorer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespacePoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespacePoliciesResponse) ProtoMessage() {}

func (x *GetNamespacePoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_explorer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespacePoliciesResponse.ProtoReflect.Descriptor instead.
func (*GetNamespacePoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_explorer_proto_rawDescGZIP(), []int{14}
}

func (x *GetNamespacePoliciesResponse) GetPolicies() []*NamespacePolicyRow {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_api_proto_explorer_proto protoreflect.FileDescriptor

const file_api_proto_explorer_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/explorer.proto\x12\n" +
	"explorerv1\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x16GetBlockHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\"e\n" +
	"\x11ListBlocksRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x88\x01\n" +
	"\fBlockSummary\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x05R\atxCount\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\fR\fpreviousHash\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\fR\bdataHash\"F\n" +
	"\x12ListBlocksResponse\x120\n" +
	"\x06blocks\x18\x01 \x03(\v2\x18.explorerv1.BlockSummaryR\x06blocks\"l\n" +
	"\x15GetBlockDetailRequest\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\btx_limit\x18\x02 \x01(\x05R\atxLimit\x12\x1b\n" +
	"\ttx_offset\x18\x03 \x01(\x05R\btxOffset\"\xc1\x01\n" +
	"\vBlockDetail\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x05R\atxCount\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\fR\fpreviousHash\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\fR\bdataHash\x128\n" +
	"\ftransactions\x18\x05 \x03(\v2\x14.explorerv1.TxDetailR\ftransactions\")\n" +
	"\x12GetTxDetailRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\xed\x02\n" +
	"\bTxDetail\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x15\n" +
	"\x06tx_num\x18\x02 \x01(\x03R\x05txNum\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\x12'\n" +
	"\x0fvalidation_code\x18\x04 \x01(\x05R\x0evalidationCode\x12<\n" +
	"\fblind_writes\x18\x05 \x03(\v2\x19.explorerv1.BlindWriteRowR\vblindWrites\x12>\n" +
	"\fendorsements\x18\x06 \x03(\v2\x1a.explorerv1.EndorsementRowR\fendorsements\x129\n" +
	"\vread_writes\x18\a \x03(\v2\x18.explorerv1.ReadWriteRowR\n" +
	"readWrites\x126\n" +
	"\n" +
	"reads_only\x18\b \x03(\v2\x17.explorerv1.ReadOnlyRowR\treadsOnly\"L\n" +
	"\rBlindWriteRow\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x8a\x01\n" +
	"\x0eEndorsementRow\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12 \n" +
	"\vendorsement\x18\x02 \x01(\fR\vendorsement\x12\x1a\n" +
	"\x06msp_id\x18\x03 \x01(\tH\x00R\x05mspId\x88\x01\x01\x12\x1a\n" +
	"\bidentity\x18\x04 \x01(\fR\bidentityB\t\n" +
	"\a_msp_id\"\x84\x01\n" +
	"\fReadWriteRow\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12&\n" +
	"\fread_version\x18\x03 \x01(\x03H\x00R\vreadVersion\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05valueB\x0f\n" +
	"\r_read_version\"_\n" +
	"\vReadOnlyRow\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x03H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\";\n" +
	"\x1bGetNamespacePoliciesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\xe6\x01\n" +
	"\x12NamespacePolicyRow\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\"\n" +
	"\fcertificates\x18\x04 \x03(\tR\fcertificates\x12\x17\n" +
	"\amsp_ids\x18\x05 \x03(\tR\x06mspIds\x12\x1c\n" +
	"\tendpoints\x18\x06 \x03(\tR\tendpoints\x12%\n" +
	"\x0ehash_algorithm\x18\a \x01(\tR\rhashAlgorithm\"Z\n" +
	"\x1cGetNamespacePoliciesResponse\x12:\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1e.explorerv1.NamespacePolicyRowR\bpolicies2\xb8\x03\n" +
	"\x14BlockExplorerService\x12L\n" +
	"\x0eGetBlockHeight\x12\x16.google.protobuf.Empty\x1a\".explorerv1.GetBlockHeightResponse\x12K\n" +
	"\n" +
	"ListBlocks\x12\x1d.explorerv1.ListBlocksRequest\x1a\x1e.explorerv1.ListBlocksResponse\x12L\n" +
	"\x0eGetBlockDetail\x12!.explorerv1.GetBlockDetailRequest\x1a\x17.explorerv1.BlockDetail\x12L\n" +
	"\x14GetTransactionDetail\x12\x1e.explorerv1.GetTxDetailRequest\x1a\x14.explorerv1.TxDetail\x12i\n" +
	"\x14GetNamespacePolicies\x12'.explorerv1.GetNamespacePoliciesRequest\x1a(.explorerv1.GetNamespacePoliciesResponseBJZHgithub.com/LF-Decentralized-Trust-labs/fabric-x-block-explorer/api/protob\x06proto3"

var (
	file_api_proto_explorer_proto_rawDescOnce sync.Once
	file_api_proto_explorer_proto_rawDescData []byte
)

func file_api_proto_explorer_proto_rawDescGZIP() []byte {
	file_api_proto_explorer_proto_rawDescOnce.Do(func() {
		file_api_proto_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_explorer_proto_rawDesc), len(file_api_proto_explorer_proto_rawDesc)))
	})
	return file_api_proto_explorer_proto_rawDescData
}

var file_api_proto_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_explorer_proto_goTypes = []any{
	(*GetBlockHeightResponse)(nil),       // 0: explorerv1.GetBlockHeightResponse
	(*ListBlocksRequest)(nil),            // 1: explorerv1.ListBlocksRequest
	(*BlockSummary)(nil),                 // 2: explorerv1.BlockSummary
	(*ListBlocksResponse)(nil),           // 3: explorerv1.ListBlocksResponse
	(*GetBlockDetailRequest)(nil),        // 4: explorerv1.GetBlockDetailRequest
	(*BlockDetail)(nil),                  // 5: explorerv1.BlockDetail
	(*GetTxDetailRequest)(nil),           // 6: explorerv1.GetTxDetailRequest
	(*TxDetail)(nil),                     // 7: explorerv1.TxDetail
	(*BlindWriteRow)(nil),                // 8: explorerv1.BlindWriteRow
	(*EndorsementRow)(nil),               // 9: explorerv1.EndorsementRow
	(*ReadWriteRow)(nil),                 // 10: explorerv1.ReadWriteRow
	(*ReadOnlyRow)(nil),                  // 11: explorerv1.ReadOnlyRow
	(*GetNamespacePoliciesRequest)(nil),  // 12: explorerv1.GetNamespacePoliciesRequest
	(*NamespacePolicyRow)(nil),           // 13: explorerv1.NamespacePolicyRow
	(*GetNamespacePoliciesResponse)(nil), // 14: explorerv1.GetNamespacePoliciesResponse
	(*emptypb.Empty)(nil),                // 15: google.protobuf.Empty
}
var file_api_proto_explorer_proto_depIdxs = []int32{
	2,  // 0: explorerv1.ListBlocksResponse.blocks:type_name -> explorerv1.BlockSummary
	7,  // 1: explorerv1.BlockDetail.transactions:type_name -> explorerv1.TxDetail
	8,  // 2: explorerv1.TxDetail.blind_writes:type_name -> explorerv1.BlindWriteRow
	9,  // 3: explorerv1.TxDetail.endorsements:type_name -> explorerv1.EndorsementRow
	10, // 4: explorerv1.TxDetail.read_writes:type_name -> explorerv1.ReadWriteRow
	11, // 5: explorerv1.TxDetail.reads_only:type_name -> explorerv1.ReadOnlyRow
	13, // 6: explorerv1.GetNamespacePoliciesResponse.policies:type_name -> explorerv1.NamespacePolicyRow
	15, // 7: explorerv1.BlockExplorerService.GetBlockHeight:input_type -> google.protobuf.Empty
	1,  // 8: explorerv1.BlockExplorerService.ListBlocks:input_type -> explorerv1.ListBlocksRequest
	4,  // 9: explorerv1.BlockExplorerService.GetBlockDetail:input_type -> explorerv1.GetBlockDetailRequest
	6,  // 10: explorerv1.BlockExplorerService.GetTransactionDetail:input_type -> explorerv1.GetTxDetailRequest
	12, // 11: explorerv1.BlockExplorerService.GetNamespacePolicies:input_type -> explorerv1.GetNamespacePoliciesRequest
	0,  // 12: explorerv1.BlockExplorerService.GetBlockHeight:output_type -> explorerv1.GetBlockHeightResponse
	3,  // 13: explorerv1.BlockExplorerService.ListBlocks:output_type -> explorerv1.ListBlocksResponse
	5,  // 14: explorerv1.BlockExplorerService.GetBlockDetail:output_type -> explorerv1.BlockDetail
	7,  // 15: explorerv1.BlockExplorerService.GetTransactionDetail:output_type -> explorerv1.TxDetail
	14, // 16: explorerv1.BlockExplorerService.GetNamespacePolicies:output_type -> explorerv1.GetNamespacePoliciesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_explorer_proto_init() }
func file_api_proto_explorer_proto_init() {
	if File_api_proto_explorer_proto != nil {
		return
	}
	file_api_proto_explorer_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_explorer_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_explorer_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_explorer_proto_rawDesc), len(file_api_proto_explorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_explorer_proto_goTypes,
		DependencyIndexes: file_api_proto_explorer_proto_depIdxs,
		MessageInfos:      file_api_proto_explorer_proto_msgTypes,
	}.Build()
	File_api_proto_explorer_proto = out.File
	file_api_proto_explorer_proto_goTypes = nil
	file_api_proto_explorer_proto_depIdxs = nil
}
