// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/api/proto/explorer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockHeightRequest - empty request
type BlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeightRequest) Reset() {
	*x = BlockHeightRequest{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightRequest) ProtoMessage() {}

func (x *BlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightRequest.ProtoReflect.Descriptor instead.
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{0}
}

// BlockHeightResponse contains the current block height
type BlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeightResponse) Reset() {
	*x = BlockHeightResponse{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightResponse) ProtoMessage() {}

func (x *BlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightResponse.ProtoReflect.Descriptor instead.
func (*BlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeightResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// GetBlockRequest to fetch a block by number
type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	LimitTx       int32                  `protobuf:"varint,2,opt,name=limit_tx,json=limitTx,proto3" json:"limit_tx,omitempty"`                // max transactions to return
	OffsetTx      int32                  `protobuf:"varint,3,opt,name=offset_tx,json=offsetTx,proto3" json:"offset_tx,omitempty"`             // transaction offset
	LimitWrites   int32                  `protobuf:"varint,4,opt,name=limit_writes,json=limitWrites,proto3" json:"limit_writes,omitempty"`    // max writes per transaction
	OffsetWrites  int32                  `protobuf:"varint,5,opt,name=offset_writes,json=offsetWrites,proto3" json:"offset_writes,omitempty"` // write offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockRequest) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *GetBlockRequest) GetLimitTx() int32 {
	if x != nil {
		return x.LimitTx
	}
	return 0
}

func (x *GetBlockRequest) GetOffsetTx() int32 {
	if x != nil {
		return x.OffsetTx
	}
	return 0
}

func (x *GetBlockRequest) GetLimitWrites() int32 {
	if x != nil {
		return x.LimitWrites
	}
	return 0
}

func (x *GetBlockRequest) GetOffsetWrites() int32 {
	if x != nil {
		return x.OffsetWrites
	}
	return 0
}

// BlockResponse contains block details
type BlockResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BlockNum      int64                    `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxCount       int32                    `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	PreviousHash  string                   `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	DataHash      string                   `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Transactions  []*TransactionWithWrites `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *BlockResponse) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockResponse) GetTxCount() int32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockResponse) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *BlockResponse) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *BlockResponse) GetTransactions() []*TransactionWithWrites {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// TransactionWithWrites contains transaction and its write sets
type TransactionWithWrites struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlockNum       int64                  `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum          int64                  `protobuf:"varint,3,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	TxId           string                 `protobuf:"bytes,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ValidationCode int64                  `protobuf:"varint,5,opt,name=validation_code,json=validationCode,proto3" json:"validation_code,omitempty"`
	Writes         []*WriteRecord         `protobuf:"bytes,6,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionWithWrites) Reset() {
	*x = TransactionWithWrites{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionWithWrites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionWithWrites) ProtoMessage() {}

func (x *TransactionWithWrites) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionWithWrites.ProtoReflect.Descriptor instead.
func (*TransactionWithWrites) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionWithWrites) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionWithWrites) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *TransactionWithWrites) GetTxNum() int64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *TransactionWithWrites) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionWithWrites) GetValidationCode() int64 {
	if x != nil {
		return x.ValidationCode
	}
	return 0
}

func (x *TransactionWithWrites) GetWrites() []*WriteRecord {
	if x != nil {
		return x.Writes
	}
	return nil
}

// WriteRecord contains a single write record
type WriteRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NamespaceId   int64                  `protobuf:"varint,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	BlockNum      int64                  `protobuf:"varint,3,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum         int64                  `protobuf:"varint,4,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	TxId          string                 `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRecord) Reset() {
	*x = WriteRecord{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRecord) ProtoMessage() {}

func (x *WriteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRecord.ProtoReflect.Descriptor instead.
func (*WriteRecord) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *WriteRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WriteRecord) GetNamespaceId() int64 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *WriteRecord) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *WriteRecord) GetTxNum() int64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *WriteRecord) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *WriteRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GetTransactionRequest to fetch transaction by ID
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // hex encoded transaction ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// TransactionResponse contains transaction with block context
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionWithWrites `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Block         *BlockHeader           `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionResponse) GetTransaction() *TransactionWithWrites {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionResponse) GetBlock() *BlockHeader {
	if x != nil {
		return x.Block
	}
	return nil
}

// BlockHeader contains basic block information
type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      int64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxCount       int32                  `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	DataHash      string                 `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{8}
}

func (x *BlockHeader) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockHeader) GetTxCount() int32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockHeader) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *BlockHeader) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

// HealthRequest - empty request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{9}
}

// HealthResponse contains service health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_explorer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_explorer_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_pkg_api_proto_explorer_proto protoreflect.FileDescriptor

const file_pkg_api_proto_explorer_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/api/proto/explorer.proto\x12\bexplorer\"\x14\n" +
	"\x12BlockHeightRequest\"-\n" +
	"\x13BlockHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\"\xae\x01\n" +
	"\x0fGetBlockRequest\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\blimit_tx\x18\x02 \x01(\x05R\alimitTx\x12\x1b\n" +
	"\toffset_tx\x18\x03 \x01(\x05R\boffsetTx\x12!\n" +
	"\flimit_writes\x18\x04 \x01(\x05R\vlimitWrites\x12#\n" +
	"\roffset_writes\x18\x05 \x01(\x05R\foffsetWrites\"\xce\x01\n" +
	"\rBlockResponse\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x05R\atxCount\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\tR\fpreviousHash\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\tR\bdataHash\x12C\n" +
	"\ftransactions\x18\x05 \x03(\v2\x1f.explorer.TransactionWithWritesR\ftransactions\"\xc8\x01\n" +
	"\x15TransactionWithWrites\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tblock_num\x18\x02 \x01(\x03R\bblockNum\x12\x15\n" +
	"\x06tx_num\x18\x03 \x01(\x03R\x05txNum\x12\x13\n" +
	"\x05tx_id\x18\x04 \x01(\tR\x04txId\x12'\n" +
	"\x0fvalidation_code\x18\x05 \x01(\x03R\x0evalidationCode\x12-\n" +
	"\x06writes\x18\x06 \x03(\v2\x15.explorer.WriteRecordR\x06writes\"\xb1\x01\n" +
	"\vWriteRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\x03R\vnamespaceId\x12\x1b\n" +
	"\tblock_num\x18\x03 \x01(\x03R\bblockNum\x12\x15\n" +
	"\x06tx_num\x18\x04 \x01(\x03R\x05txNum\x12\x13\n" +
	"\x05tx_id\x18\x05 \x01(\tR\x04txId\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\",\n" +
	"\x15GetTransactionRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\x85\x01\n" +
	"\x13TransactionResponse\x12A\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1f.explorer.TransactionWithWritesR\vtransaction\x12+\n" +
	"\x05block\x18\x02 \x01(\v2\x15.explorer.BlockHeaderR\x05block\"\x87\x01\n" +
	"\vBlockHeader\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x03R\bblockNum\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x05R\atxCount\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\tR\fpreviousHash\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\tR\bdataHash\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails2\xb2\x02\n" +
	"\rBlockExplorer\x12M\n" +
	"\x0eGetBlockHeight\x12\x1c.explorer.BlockHeightRequest\x1a\x1d.explorer.BlockHeightResponse\x12>\n" +
	"\bGetBlock\x12\x19.explorer.GetBlockRequest\x1a\x17.explorer.BlockResponse\x12P\n" +
	"\x0eGetTransaction\x12\x1f.explorer.GetTransactionRequest\x1a\x1d.explorer.TransactionResponse\x12@\n" +
	"\vHealthCheck\x12\x17.explorer.HealthRequest\x1a\x18.explorer.HealthResponseBNZLgithub.com/LF-Decentralized-Trust-labs/fabric-x-block-explorer/pkg/api/protob\x06proto3"

var (
	file_pkg_api_proto_explorer_proto_rawDescOnce sync.Once
	file_pkg_api_proto_explorer_proto_rawDescData []byte
)

func file_pkg_api_proto_explorer_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_explorer_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_explorer_proto_rawDesc), len(file_pkg_api_proto_explorer_proto_rawDesc)))
	})
	return file_pkg_api_proto_explorer_proto_rawDescData
}

var file_pkg_api_proto_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_api_proto_explorer_proto_goTypes = []any{
	(*BlockHeightRequest)(nil),    // 0: explorer.BlockHeightRequest
	(*BlockHeightResponse)(nil),   // 1: explorer.BlockHeightResponse
	(*GetBlockRequest)(nil),       // 2: explorer.GetBlockRequest
	(*BlockResponse)(nil),         // 3: explorer.BlockResponse
	(*TransactionWithWrites)(nil), // 4: explorer.TransactionWithWrites
	(*WriteRecord)(nil),           // 5: explorer.WriteRecord
	(*GetTransactionRequest)(nil), // 6: explorer.GetTransactionRequest
	(*TransactionResponse)(nil),   // 7: explorer.TransactionResponse
	(*BlockHeader)(nil),           // 8: explorer.BlockHeader
	(*HealthRequest)(nil),         // 9: explorer.HealthRequest
	(*HealthResponse)(nil),        // 10: explorer.HealthResponse
}
var file_pkg_api_proto_explorer_proto_depIdxs = []int32{
	4,  // 0: explorer.BlockResponse.transactions:type_name -> explorer.TransactionWithWrites
	5,  // 1: explorer.TransactionWithWrites.writes:type_name -> explorer.WriteRecord
	4,  // 2: explorer.TransactionResponse.transaction:type_name -> explorer.TransactionWithWrites
	8,  // 3: explorer.TransactionResponse.block:type_name -> explorer.BlockHeader
	0,  // 4: explorer.BlockExplorer.GetBlockHeight:input_type -> explorer.BlockHeightRequest
	2,  // 5: explorer.BlockExplorer.GetBlock:input_type -> explorer.GetBlockRequest
	6,  // 6: explorer.BlockExplorer.GetTransaction:input_type -> explorer.GetTransactionRequest
	9,  // 7: explorer.BlockExplorer.HealthCheck:input_type -> explorer.HealthRequest
	1,  // 8: explorer.BlockExplorer.GetBlockHeight:output_type -> explorer.BlockHeightResponse
	3,  // 9: explorer.BlockExplorer.GetBlock:output_type -> explorer.BlockResponse
	7,  // 10: explorer.BlockExplorer.GetTransaction:output_type -> explorer.TransactionResponse
	10, // 11: explorer.BlockExplorer.HealthCheck:output_type -> explorer.HealthResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_explorer_proto_init() }
func file_pkg_api_proto_explorer_proto_init() {
	if File_pkg_api_proto_explorer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_explorer_proto_rawDesc), len(file_pkg_api_proto_explorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_explorer_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_explorer_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_explorer_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_explorer_proto = out.File
	file_pkg_api_proto_explorer_proto_goTypes = nil
	file_pkg_api_proto_explorer_proto_depIdxs = nil
}
