// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: pkg/api/proto/explorer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockExplorer_GetBlockHeight_FullMethodName = "/explorer.BlockExplorer/GetBlockHeight"
	BlockExplorer_GetBlock_FullMethodName       = "/explorer.BlockExplorer/GetBlock"
	BlockExplorer_GetTransaction_FullMethodName = "/explorer.BlockExplorer/GetTransaction"
	BlockExplorer_HealthCheck_FullMethodName    = "/explorer.BlockExplorer/HealthCheck"
)

// BlockExplorerClient is the client API for BlockExplorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlockExplorer service provides APIs to query blockchain data
type BlockExplorerClient interface {
	// GetBlockHeight returns the current block height
	GetBlockHeight(ctx context.Context, in *BlockHeightRequest, opts ...grpc.CallOption) (*BlockHeightResponse, error)
	// GetBlock returns block details by block number
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetTransaction returns transaction details by transaction ID
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// HealthCheck returns service health status
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type blockExplorerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockExplorerClient(cc grpc.ClientConnInterface) BlockExplorerClient {
	return &blockExplorerClient{cc}
}

func (c *blockExplorerClient) GetBlockHeight(ctx context.Context, in *BlockHeightRequest, opts ...grpc.CallOption) (*BlockHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockHeightResponse)
	err := c.cc.Invoke(ctx, BlockExplorer_GetBlockHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, BlockExplorer_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, BlockExplorer_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockExplorerClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BlockExplorer_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockExplorerServer is the server API for BlockExplorer service.
// All implementations must embed UnimplementedBlockExplorerServer
// for forward compatibility.
//
// BlockExplorer service provides APIs to query blockchain data
type BlockExplorerServer interface {
	// GetBlockHeight returns the current block height
	GetBlockHeight(context.Context, *BlockHeightRequest) (*BlockHeightResponse, error)
	// GetBlock returns block details by block number
	GetBlock(context.Context, *GetBlockRequest) (*BlockResponse, error)
	// GetTransaction returns transaction details by transaction ID
	GetTransaction(context.Context, *GetTransactionRequest) (*TransactionResponse, error)
	// HealthCheck returns service health status
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBlockExplorerServer()
}

// UnimplementedBlockExplorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockExplorerServer struct{}

func (UnimplementedBlockExplorerServer) GetBlockHeight(context.Context, *BlockHeightRequest) (*BlockHeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockHeight not implemented")
}
func (UnimplementedBlockExplorerServer) GetBlock(context.Context, *GetBlockRequest) (*BlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedBlockExplorerServer) GetTransaction(context.Context, *GetTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBlockExplorerServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBlockExplorerServer) mustEmbedUnimplementedBlockExplorerServer() {}
func (UnimplementedBlockExplorerServer) testEmbeddedByValue()                       {}

// UnsafeBlockExplorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockExplorerServer will
// result in compilation errors.
type UnsafeBlockExplorerServer interface {
	mustEmbedUnimplementedBlockExplorerServer()
}

func RegisterBlockExplorerServer(s grpc.ServiceRegistrar, srv BlockExplorerServer) {
	// If the following call panics, it indicates UnimplementedBlockExplorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockExplorer_ServiceDesc, srv)
}

func _BlockExplorer_GetBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServer).GetBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorer_GetBlockHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServer).GetBlockHeight(ctx, req.(*BlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorer_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorer_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorer_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorer_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockExplorer_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockExplorerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockExplorer_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockExplorerServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockExplorer_ServiceDesc is the grpc.ServiceDesc for BlockExplorer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockExplorer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explorer.BlockExplorer",
	HandlerType: (*BlockExplorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockHeight",
			Handler:    _BlockExplorer_GetBlockHeight_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BlockExplorer_GetBlock_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BlockExplorer_GetTransaction_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _BlockExplorer_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/explorer.proto",
}
